### ISSUE TITLE
List current todos?

### ISSUE THREAD

**Issue by Barbaross93** [wakatara/rofi-org-todo#1]
Hello,

Thanks for sharing this script! It's almost exactly what I was looking for. I was wondering if it's possible to have it list the current todos, and as you type, you have a todo thats already in the list  so that it can be selected and then modified? Sort of like this script: https://github.com/claudiodangelis/rofi-todo

Thanks again!

**Comment by wakatara** [comment]
Hey @Barbarossa93 !

Thanks for the kind words. Tbh, the model between the other app and emacs is quite different making that a slightly inviable option.

The big difference between the rofi-todo script is that todo.sh has one file that contains all the todos. Emacs org-mode is has a slightly different model where you can place a `TODO` keyword (or others... I have 5) in any `.org` file and then the emacs agenda mode will literally parse all your files and suck those into a nice view (this can take sevral seconds some times until it caches.). Literally, I just archived some files the other day and I think I have over 250 files. 

So, the purpose of this script is simply to get things into a Inbox file (a la David Allen's Getting Things Done method) and then use all the very powerful features of emacs to manage it (refiling, setting deadlines, retagging etc etc.). Features I'm considering adding are having a way to parse deadlines or scheduled dates, automatically link URLs in a note and such, but the goal of this rofi script is not to centrally manage todos for you. I'd expect that in emacs. (so while my pride hurts saying it, you may be better off going with rofi-todo if your todo lists are simpler and not as voluminous). 

(so practically there would be a lot of difficulties due to the way TODOs work in org mode, not to mention how to filter the list for scheduled or deadlined TODOs in the far future - for example, I have a slew of those for things as varied as getting a flu shot to invoicing.).

Sorry it's not a more supportive answer. I *would* recommend digging down into emacs org-mode for organizing more. I have to admit, I was *deeply* sceptical of using it being a big fan of Taskpaper (which you might want to check out also as there is an emacs plugin in for it and a very simiilar mode in VS Code) and the dman thing basically runs my life now... =p 

stay safe and healthy.

**Comment by biffbaxter** [comment]
I would recommend a look at org super agenda if you want to really customize views of tasks in emacs. I use it simply to break up my tasks by region (as I work in multiple geographic regions) and I can then group my todos scattered about automagically by tagging in a consolidated list - https://github.com/alphapapa/org-super-agenda - warning - it can be a bit of a rabbit hole (what in emacs is not) but once setup its great.

**Comment by wakatara** [comment]
@biffbaxter Thanks for the reco! Though I am a big fan if `org-super-agenda`. I have a [pretty nice setup that works for me](https://daryl.wakatara.com/a-better-gtd-and-crm-flow-for-emacs-org-mode/), but org-contacts often makes it slow (so should try org-roam) and have to admit I've been looking at Notion and roam-research a bit of late due to having to interact with so many other people at my new roel remotely (see latest blog posts.). 
Right now, experimenting, but also want to see if org-roam can fix the org-contacts CRM problem I currently have as well as sort me out on experimenting on the zettelkasten front. On verra.

**Comment by wakatara** [comment]
So, @Barabarossa93, this would be a WONTFIX. Hope that's alright. I imagine there might be some other tools out there which suit you better than org-mode if you need to list everything (I did like the idea of listing all the `TODO`s in, say an inbox.org file if people are using that for quick capture, but not sure it adds that much value.

If org-mode with scattered files is problematic I would suggest the taskpaper emacs implementation. I was a taskpaper user for years and still think it's a great system. My guess is also it would be easy(ier) to rig something up in rofi to grab the single file, and then filter and manipulate the list before writing it back. 

Interested in what you ended up going with though as I imagine org-mode without emacs agenda or org-super-agenda fronting it means that rofi and emacs might not be what you're looking for. Did you try out the simple todo.sh rofi script and see if it met your needs?
